Feature/improve requesting feedback 177
wearespindle/flindt-front-end pull request #3
Opened 2018-02-05 13:24 UTC by TomOffringa

Wait with merge until backend fixed 177 in API.

2018-02-05 13:47 UTC, PM5544 requested changes
Besides these point 👍🏻

2018-02-05 13:47 UTC, PM5544 commented on src/pages/AskFeedback.js
> +        <option key="none_1337" value="none">
key attributes are only needed for JSX elements created inside a loop (via map ors something), without this this becomes a one-liner and the parenthesis are also removed by Prettier.
And can you rename the value of the <option> to "no_circle", I think this adds clarity especially in the render where this value is checked.

2018-02-05 13:47 UTC, PM5544 commented on src/pages/AskFeedback.js
> +    if (value === 'none') {
change this value to "no_circle"?

2018-02-05 13:53 UTC, PM5544 commented
awesomesauce

2018-02-05 13:53 UTC, TomOffringa commented
Please wait with merging until https://github.com/wearespindle/flindt/pull/72 is merged and deployed.

2018-02-06 07:19 UTC, PM5544 approved these changes

2018-02-06 13:49 UTC, PM5544 requested changes

2018-02-06 13:49 UTC, PM5544 commented on src/pages/AskFeedback.js
> +        <option value="no_cirlce">No Specific Circle</option>
oopsie a typo :) 'no_cirlce' ==> 'no_circle'

2018-02-06 14:43 UTC, PM5544 submitted a review, later dismissed

2018-02-07 08:07 UTC, closed without merging